global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kubernetes-system'
    scrape_interval: 5s
    static_configs:
      - targets: ['158.160.109.229:31000']

  - job_name: 'kube-state-metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['158.160.109.229:31001']

  - job_name: 'frontend'
    scrape_interval: 5s
    static_configs:
      - targets: ['158.160.109.229:30200']

  - job_name: 'backend'
    scrape_interval: 5s
    static_configs:
      - targets: ['158.160.109.229:31002']
